# Generated by Django 5.2.6 on 2025-10-21 23:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo_animal', models.CharField(choices=[('Cavalo', 'Cavalo'), ('Bovino', 'Bovino'), ('Ovelha', 'Ovelha'), ('Porco', 'Porco'), ('Galinha', 'Galinha')], default='Cavalo', max_length=50)),
                ('tipo', models.CharField(choices=[('Normal', 'Normal'), ('Premium', 'Premium')], max_length=50)),
                ('peso', models.CharField(choices=[('500g', '500g'), ('1kg', '1kg'), ('2kg', '2kg'), ('5kg', '5kg'), ('10kg', '10kg'), ('20kg', '20kg'), ('25kg', '25kg')], max_length=20)),
                ('quantidade', models.PositiveIntegerField(default=0, verbose_name='Quantidade em Estoque')),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Preço Unitário (R$)')),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_vendida', models.PositiveIntegerField()),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_dash.produto')),
            ],
        ),
    ]
