# Generated by Django 5.2.7 on 2025-10-18 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='tipo_animal',
            field=models.CharField(choices=[('Cachorro', 'Cachorro'), ('Gato', 'Gato')], default='Cachorro', max_length=50),
        ),
        migrations.AlterField(
            model_name='produto',
            name='peso',
            field=models.CharField(choices=[('500g', '500g'), ('1kg', '1kg')], max_length=20),
        ),
    ]
