# Generated by Django 5.2.7 on 2025-10-19 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dash', '0002_produto_tipo_animal_alter_produto_peso'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='produto',
            name='peso',
            field=models.CharField(choices=[('500g', '500g'), ('1kg', '1kg'), ('2kg', '2kg'), ('5kg', '5kg'), ('10kg', '10kg'), ('20kg', '20kg'), ('25kg', '25kg')], max_length=20),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tipo_animal',
            field=models.CharField(choices=[('Cavalo', 'Cavalo'), ('Bovino', 'Bovino'), ('Ovelha', 'Ovelha'), ('Porco', 'Porco'), ('Galinha', 'Galinha')], default='Cavalo', max_length=50),
        ),
    ]
