# Generated by Django 5.2.7 on 2025-10-19 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dash', '0003_produto_preco_alter_produto_peso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
